Bugzilla.pm, Bugzilla/Install/Util.pm
Discussion on [Bug 1302755 - Optimize request_cache() more](https://bugzilla.mozilla.org/show_bug.cgi?id=1302755)
=> Bug 1302755 - Optimize request_cache() more

Bugzilla/Template.pm, template/en/default/global/header.html.tmpl
Discussion on [Bug 1309884](https://bugzilla.mozilla.org/show_bug.cgi?id=1309884)
=> Bug 1309884 - constants.CONCATENATE_ASSETS gets constant folded when true

template/en/default/list/list.html.tmpl
I didn't test this yet since the docker instructions aren't very good and my docker image is still building. It seems trivial enough that I'm putting it for review anyways.
r? @dylanwh
=> Bug 1332976 - Include quicksearch query string in the buglist.cgi title

Bugzilla.pm, Bugzilla/Attachment.pm, Bugzilla/Bug.pm, Bugzilla/Comment.pm
Discussion on [Bug 1301951 - Fix Bugzilla::Bug memory leaks](https://bugzilla.mozilla.org/show_bug.cgi?id=1301951)
=> Bug 1301951 - Fix Bugzilla::Bug memory leaks

Bugzilla.pm, Bugzilla/Auth.pm, Bugzilla/Auth/Login/APIKey.pm, Bugzilla/Auth/Login/Cookie.pm, Bugzilla/Auth/Login/Env.pm, Bugzilla/Auth/Persist/Cookie.pm, Bugzilla/Auth/Verify.pm, Bugzilla/Auth/Verify/DB.pm, Bugzilla/CGI.pm, Bugzilla/Constants.pm, Bugzilla/DB/Schema.pm, Bugzilla/Token.pm, extensions/GitHubAuth/Config.pm, extensions/GitHubAuth/Extension.pm, extensions/GitHubAuth/lib/Client.pm, extensions/GitHubAuth/lib/Client/Error.pm, extensions/GitHubAuth/lib/Config.pm, extensions/GitHubAuth/lib/Login.pm, extensions/GitHubAuth/lib/Verify.pm, extensions/GitHubAuth/template/en/default/account/auth/github-verify-account.html.tmpl, extensions/GitHubAuth/template/en/default/admin/params/githubauth.html.tmpl, extensions/GitHubAuth/template/en/default/hook/account/auth/login-additional_methods.html.tmpl, extensions/GitHubAuth/template/en/default/hook/account/auth/login-small-additional_methods.html.tmpl, extensions/GitHubAuth/template/en/default/hook/global/code-error-errors.html.tmpl, extensions/GitHubAuth/template/en/default/hook/global/user-error-errors.html.tmpl, github.cgi
Backport of the GitHub Authentication work done by @dylanwh for Mozilla BMO. Adjusted to integrate cleanly with BZ master branch.
=> GitHub Authentication for BZ master branch

contrib/jb2bz.py
=> Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1427623 by setting

contrib/jb2bz.py
=> bug 1429243 - Fix default values for version and op_sys when importing

Bugzilla/Hook.pm, Bugzilla/Template.pm, extensions/Example/Extension.pm
We have this in bmo/harmony, and it seems pretty safe to backport it.
=> add a new hook: template_after_create

template/en/default/list/list.html.tmpl
Bugzilla ID - [1226123](https://bugzilla.mozilla.org/show_bug.cgi?id=1226123)
=> Email addresses with an apostrophe handler

template/en/default/setup/strings.txt.pl
Changed "make all" to "convert"
=> Bug 364693

Bugzilla/DB/Schema.pm, Bugzilla/DB/Schema/Mysql.pm, Bugzilla/DB/Schema/Oracle.pm, Bugzilla/DB/Schema/Pg.pm, Bugzilla/DB/Schema/Sqlite.pm
This changes the Schema classes enough so they use Moo, which will allow adding a weak reference to the database connection
=> Make Bugzilla::DB::Schema and subclasses Moo-based classes.

docs/en/rst/about/index.rst
Hello, :smiley:
I updated the `docs/en/rst/about/index.rst` file. :pencil:
*Yours,*
[**Suriyaa**](https://mozillians.org/de/u/suriyaakudo/) 🦊 
(*PS: Is somebody interested to vouch me at https://mozillians.org/de/u/suriyaakudo/?*)
=> Bug #1470459 - Use HTTPS protocol

.github/pull_request_template.md, .github/workflows/release.yml, t/002goodperl.t, t/003safesys.t, t/004template.t, t/005whitespace.t, t/006spellcheck.t, t/007util.t, t/009bugwords.t, t/010dependencies.t, t/011pod.t
* Add GitHub Actions to run tests on commit
* Fix tests for compatibility with Perl 5.30
=> Bug 1785938: Make tests work in GHA on 4.4 branch

README
Putting it in the README makes it show up on GitHub when that branch is selected.
=> Update README to list abandoned status

Bugzilla/Util.pm
Added documentation for all undocumented functions in Bugzilla::Util
* [bmo#1644654](https://bugzilla.mozilla.org/show_bug.cgi?id=1644654)
=> Fixed pod in Bugzilla/Util.pm

docs/en/rst/conf.py, docs/en/rst/installing/linux.rst, docs/en/rst/installing/mysql.rst, docs/en/rst/installing/quick-start.rst
See [bug 1851235](https://bugzilla.mozilla.org/show_bug.cgi?id=1851235)
=> Bug 1851235: Make docs build on Sphinx 7.2.5

.readthedocs.yaml, docs/en/rst/conf.py, docs/makedocs.pl
See [Bug 1769248](https://bugzilla.mozilla.org/show_bug.cgi?id=1769248)
=> [5.0.4] Bug 1769248: get ReadTheDocs to build the POD docs

.readthedocs.yaml, docs/en/rst/conf.py, docs/makedocs.pl
See [Bug 1769248](https://bugzilla.mozilla.org/show_bug.cgi?id=1769248)
=> [5.2] Bug 1769248: get ReadTheDocs to build the POD docs

t/001compile.t
See [Bug 1851412](https://bugzilla.mozilla.org/show_bug.cgi?id=1851412)
=> Bug 1851412: fix warning in 001compile test

Bugzilla/Install/Requirements.pm
See [Bug 1560873](https://bugzilla.mozilla.org/show_bug.cgi?id=1560873)
=> [5.2] Bug 1560873: require Template-Toolkit 3.008

testserver.pl
See [Bug 1851398](https://bugzilla.mozilla.org/show_bug.cgi?id=1851398)
=> [5.2] Bug 1851398: Allow testserver.pl to work with self-signed certs

Bugzilla/Constants.pm, Bugzilla/DB.pm, Bugzilla/Install/Requirements.pm, Build.PL, docs/en/rst/installing/essential-post-install-config.rst, t/004template.t, template/en/default/config.js.tmpl, template/en/default/setup/strings.txt.pl
See [Bug 1851354](https://bugzilla.mozilla.org/show_bug.cgi?id=1851354)
This is the same patch dylan already r+'d on the bug.
=> [5.0.4] Bug 1851354: blocklist MySQL 8+, offer MariaDB

.github/pull_request_template.md
* [bmo#1893853](https://bugzilla.mozilla.org/show_bug.cgi?id=1893853)
=> Bug 1893853: make request for bug number explicit on pull request template

Bugzilla/DB.pm
* [bug#1896338](https://bugzilla.mozilla.org/show_bug.cgi?id=1896338)
=> Bug 1896338: properly detect if the DB already exists during setup

Bugzilla.pm
* [bug#1588175](https://bugzilla.mozilla.org/show_bug.cgi?id=1588175)
=> Bug 1588175 - Undefined subroutine utf8::SWASHNEW called at Bugzilla/Util.pm line 109.

template/en/default/setup/strings.txt.pl
* [bug#1896576](https://bugzilla.mozilla.org/show_bug.cgi?id=1896576)
=> Bug 1896576: tell the user to re-run checksetup.pl after changing db_driver

docs/en/rst/installing/quick-start.rst
* [bug#1896579](https://bugzilla.mozilla.org/show_bug.cgi?id=1896579)
=> Bug 1896579: Update QuickStart for new MariaDB driver

Bugzilla/DB/MariaDB.pm, Bugzilla/DB/Mysql.pm
* [bug#1898161](https://bugzilla.mozilla.org/show_bug.cgi?id=1898161)
=> [5.2] Bug 1898161: fix utf8-conversion on MySQL 8

docker/mysql/bugzilla.cnf, docs/en/rst/installing/mariadb.rst, docs/en/rst/installing/quick-start.rst, template/en/default/setup/strings.txt.pl
* [bug#1896600](https://bugzilla.mozilla.org/show_bug.cgi?id=1896600)
=> Bug 1896600: MariaDB <10.6 wants ON instead of 1 in config options

.github/pull_request_template.md
This one actually puts in a branch lockdown message since it's security and stability fixes only.
* [bug#1897545](https://bugzilla.mozilla.org/show_bug.cgi?id=1897545)
=> [4.4] Bug 1897545: User-friendly pull request template

.github/pull_request_template.md
More user-friendly pull request template.
* [bug#1897545](https://bugzilla.mozilla.org/show_bug.cgi?id=1897545)
=> [5.2] Bug 1897545: More user-friendly pull request template

Bugzilla/Install/DB.pm
Fix foreign key reference error.
* [bug#1902375](https://bugzilla.mozilla.org/show_bug.cgi?id=1902375)
1. Install Bugzilla 2.18rc3 on MySQL 5.7
2. mysqldump the database and restore it to MariaDB 10.6
3. Install Bugzilla 5.2 and point it at the MariaDB instance
4. run checksetup.pl
=> [5.2] Bug 1902375: fix foreignkey error upgrading from <3.0 to >=5.0.6

template/en/default/pages/release-notes.html.tmpl
* [bug#1786956](https://bugzilla.mozilla.org/show_bug.cgi?id=1786956)
=> Bug 1786956: Release notes for Bugzilla 5.0.4.1
