Bugzilla/Extension.pm

Currently, anything that is loaded after the bugzilla extensions
are loaded has to search through each callback inserted into @INC
by Bugzilla::Extension. If you have a lot of extensions this is slow.
It is harmless to search for Bugzilla::Extension::* modules last, so
we replace the unshift with a push.

Bug 1283612 - Add Bugzilla::Extension module loader last

---

Bugzilla/CGI.pm

[Bug 1303896](https://bugzilla.mozilla.org/show_bug.cgi?id=1303896)

Bug 1303896 - Fix "Can't locate object method 'host' via package 'URI::_generic'"

---

Bugzilla/Migrate.pm
Bugzilla/Util.pm

Discussion on [Bug 1300437](https://bugzilla.mozilla.org/show_bug.cgi?id=1300437)

Bug 1300437 - DateTime::TimeZone::offset_as_string called incorrectly

---

Bugzilla/API/1_0/Server.pm

Fix [Bug 1309737](https://bugzilla.mozilla.org/show_bug.cgi?id=1309737) - Add User-Agent to the Access-Control-Allow-Headers header

Bug 1309737 - Add User-Agent to the Access-Control-Allow-Headers header

---

Bugzilla/Bug.pm

Timetrack fields, "Orig Est."+"Hours Left", accept numbers with commas or point
For non-US locales the bug entry/update page shows values with commas as decimal seperator in the timetracking fields "Orig Est." and "Hours Left". However when saving/updating bugzilla refuses these values. (see bug 1122419)
These 2 changed lines let bugzilla accept/process these "comma-values" as "point-values".
This patch *should* not influence systems with US locale.

Bug 1122419 - Numeric values used in timetracking fields do not accept a comma: 5,0 instead of 5.0 doesn't work

---

Bugzilla/API/1_0/Server.pm

Use datetime_format_inbound from Bugzilla::API::1_0::Util package.

Bug 1317777 - REST API 1.0 - datetime inputs cause server error

---

skins/standard/bug.css

This commit fixes bug #1287265. 
https://bugzilla.mozilla.org/show_bug.cgi?id=1287265

Bug 1287265 - Need a grippy for Preview at Description/Additional Comments 

---

contrib/jb2bz.py

Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1427626
Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1427638
Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1427664
Convert jb2bz to use "email" module rather than rfc822, multifile,
mimetools, and StringIO for easier manipulation of the mailbox objects.
This fixed (among other things) 1427626 as the Subject of the email is
now obtained correctly.
Fix the date formatting throughout to always use UTC, which is what
Bugzilla expects for the dates.  This fixed 1427638.
Fix attachment processing, which was using multifile rather than walking
the parts of the email object.  This fixed part of 1427664
Fix the fact that the process_reply_file function never checked for
attachments in any followups.  This fixed part of 1427664
Fix …

Significant update to jb2bz.py.

---

template/en/default/flag/list.html.tmpl

After https://github.com/bugzilla/bugzilla/commit/7d0c10e71498f2909f466fc0ccda1890595bd3ff,
the <option> used when no flag is set is displayed as 'X' in Safari. This is because WebKit
displays the label when provided as per the latest HTML specification:
- https://html.spec.whatwg.org/multipage/rendering.html#the-select-element-2
- https://html.spec.whatwg.org/multipage/forms.html#concept-option-label
Chrome/Blink also display the label in standards mode, but not in quirks mode. The proposed
fix is to use a whitespace as label instead of 'X'. This renders as empty in Firefox / Chrome
and Safari and is still recognized as valid HTML as per https://validator.w3.org.

<option> used when no flag is set is displayed as 'X' in Safari

---

Bugzilla/DB/Schema.pm
Bugzilla/Install/DB.pm

When running this on an old schema, checksetup will print:
```
Dropping flaginclusions
Dropping foreign key: flaginclusions.type_id -> flagtypes.id...
Updating column type_id in table flaginclusions ...
Old: smallint NOT NULL
New: mediumint NOT NULL
Dropping flagexclusions
Dropping foreign key: flagexclusions.type_id -> flagtypes.id...
Updating column type_id in table flagexclusions ...
Old: smallint NOT NULL
New: mediumint NOT NULL
Dropping flags
Dropping foreign key: flags.type_id -> flagtypes.id...
Updating column type_id in table flags ...
Old: smallint NOT NULL
New: mediumint NOT NULL
Updating column id in table flagtypes ...
Old: smallint auto_increment PRIMARY KEY NOT NULL
New: mediumint auto_increment PRIMARY KEY NOT NULL
Adding foreign key: flagexclusions.type_id -> …
```

make flagtypes id a medium int

---

template/en/default/global/header.html.tmpl

Add viewport meta to improve rendering on mobile devices. Without this meta Google Search tools would report Bugzilla pages as not suitable for mobile devices.

Add viewport meta

---

Bugzilla/DB.pm
Bugzilla/DB/Schema.pm
t/013dbschema.t

Bugzilla::DB::Schema->new() was both a normal constructor and also a class-loading factory method. It is simpler to just do the class loading at the call-site (in Bugzilla::DB::_bz_schema).
It's not very likely extensions relied on this behavior so this should be a good
change.
This is part 1 of a series of incremental patches to allow the Schema layer to access the database connection.

[Bug 1592129] remove subclass loading and driver delegation from Schema->new.

---

Bugzilla/DB.pm
Bugzilla/DB/QuoteIdentifier.pm

The Bugzilla::DB object has a qi attribute which returns a special hashref
that can be used inside double-quoted strings to quote database identifiers.
```perl
my $q = Bugzilla->dbh->qi;
Bugzilla->dbh->do("SELECT COUNT(*) FROM $q->{groups}");
```

Add a shortcut for quoting identifiers in strings.

---

Bugzilla/DB.pm
Bugzilla/DB/Schema.pm
t/013dbschema.t

This change adds a 'db' attribute to the `Bugzilla::DB::Schema` class.
In two places (`get_empty_schema` and `deserialize_abstract`) the invocant
argument was called `$class` but was never actually a class. Those were renamed
to `$self`. It was fortunate that they were always objects because otherwise it
would have been more difficult to ensure a `db` is always present.

Pass a reference to db into Schema object

---

docs/en/rst/installing/linux.rst

The documentation for installation, as-is, fails on Ubuntu 20.04. 
This update fixes  the apt commands and configures Apache for Ubuntu 20.04.  Also follows 
current practices in using MariaDB instead of MySQL. MariaDB is the new default for Debian 
distros and is a drop-in replacement for MySQL with no code changes required.
Does not include activating TLS/SSL command and a self-signed cert which would be 
`sudo a2enmod ssl`

Document Update for Ubuntu 20.04

---

README
contrib/bugzilla-submit/README
contrib/bugzilla-submit/bugzilla-submit.xml
docs/en/rst/about/index.rst
docs/en/rst/using/creating-an-account.rst
docs/en/rst/using/filing.rst
docs/en/rst/using/finding.rst

This PR updates the test playground reference to the current URL as Landfill no longer works.

Remove Landfill reference

---

docs/en/rst/installing/linux.rst
docs/en/rst/installing/mysql.rst
docs/en/rst/installing/quick-start.rst

Quick Start guide based on Ubuntu 22.04 LTS
In the Linux section, updated dependencies for Ubuntu, CentOS Stream and Fedora, as well as added openSUSE mention, since there's a Bugzilla package too.
MySQL now mentions MariaDB and recommends installing MariaDB on Windows.
5.2 specific changes, since there's one more dependency required, and you need to create a database before running the check script.

Bug 1785943: Update the MySQL, Linux and Quick Start in the Installation documentation 5.2

---

docs/en/rst/installing/linux.rst
docs/en/rst/installing/mysql.rst
docs/en/rst/installing/quick-start.rst

Quick Start guide based on Ubuntu 22.04 LTS
In the Linux section, updated dependencies for Ubuntu, CentOS Stream and Fedora, as well as added openSUSE mention, since there's a Bugzilla package too.
MySQL now mentions MariaDB and recommends installing MariaDB on Windows.

Bug 1785943: Update the MySQL, Linux and Quick Start in the Installation documentation 5.0

---

.github/pull_request_template.md
.github/workflows/release.yml
t/002goodperl.t
t/003safesys.t
t/004template.t
t/005whitespace.t
t/006spellcheck.t
t/007util.t
t/009bugwords.t
t/010dependencies.t
t/011pod.t

* Adds GitHub Actions to run tests
* Fixes tests for compatibility with Perl 5.30
Note: Tests currently have a legitimate test failure (pod coverage) which will need a separate patch on a new bug to fix.

Bug 1785938: Make tests work in GHA on 5.0.4 branch

---

.github/pull_request_template.md
.github/workflows/release.yml
t/002goodperl.t
t/003safesys.t
t/004template.t
t/005whitespace.t
t/006spellcheck.t
t/007util.t
t/009bugwords.t
t/010dependencies.t
t/011pod.t

* Run GHA tests on 5.2 branch
* update tests for compatibility with Perl 5.30
Note: there are several legitimate test failures, mostly related to `Bugzilla::DB`, which will need to be fixed on a separate bug.

Bug 1785938: Make tests work in GHA on 5.2 branch

---

docs/en/rst/installing/quick-start.rst

This PR fixes an issue with documentation, where settings didn't apply to addresses not mentioned in VirtualHost
* [bmo#1797108](https://bugzilla.mozilla.org/show_bug.cgi?id=1797108)

Move Directory out of VirtualHost (5.0)

---

docs/en/rst/installing/quick-start.rst

The apache code block directive in RST needs a blank line after it before the code starts.
* [bmo#1839072](https://bugzilla.mozilla.org/show_bug.cgi?id=1839072)

Bug 1839072: fix Apache config not showing in quickstart docs

---

.github/workflows/release.yml

See [Bug 1852497](https://bugzilla.mozilla.org/show_bug.cgi?id=1852497)

[4.4] Bug 1852497: Use actions/checkout@v4 in GitHub Actions

---

.github/workflows/release.yml

See [Bug 1852497](https://bugzilla.mozilla.org/show_bug.cgi?id=1852497)

[5.0.4] Bug 1852497: Use actions/checkout@v4 in GitHub Actions

---

.github/workflows/release.yml

See [Bug 1852497](https://bugzilla.mozilla.org/show_bug.cgi?id=1852497)

[5.2] Bug 1852497: Use actions/checkout@v4 in GitHub Actions

---

THIS_BRANCH_IS_DEAD.txt
checksetup.pl
skins/standard/global.css
template/en/default/index.html.tmpl

Note this is on the 5.0 branch not 5.0.4. Nobody will ever see this unless they git pull from a 5.0.x git checkout.
Adds the following output at the end of checksetup.pl:
Adds the following banner for admin users only on the home page:
Adds more-detailed text to the THIS_BRANCH_IS_DEAD.txt file in the root of the checkout.

[5.0] Bug 1850481: Tell 5.0 git users to use 5.2

---

Bugzilla/Update.pm

The update check code is hard-coded to assume that branches only have 2 numbers in them (i.e. 5.0, 5.2, etc).  Of course, the 5.0.4 branch has 3, and its versions will be 5.0.4.1, 5.0.4.2, etc.
So the update check has to be updated to handle it.
There's two sets of things that had to change here:
1) How to figure out which branch it's on.
2) How to parse version numbers in general so we can compare it properly with the one fed back to us by the update check.
For 1) I just opted to hardcode '5.0.4' in there. Every other branch still has the dynamic detection code, and the branch will likely never branch again, so it's not worth wasting effort making the dynamic detection work with it.
For 2) I've added an optional additional number between the main number and the rc section in the big …

Bug 1786951: Make the update check work on the 5.0.4 branch

---

Bugzilla/Install/Requirements.pm

See [Bug 1560873](https://bugzilla.mozilla.org/show_bug.cgi?id=1560873)

[5.0.4] Bug 1560873: blacklist broken versions of Template-Toolkit

---

Bugzilla/Install/Requirements.pm

See [Bug 1560873](https://bugzilla.mozilla.org/show_bug.cgi?id=1560873)

[4.4] Bug 1560873: blacklist broken versions of Template-Toolkit

---

.gitignore
skins/contrib/Dusk/admin.css
skins/contrib/Dusk/bug.css
skins/contrib/Dusk/global.css

This PR fixes color contrast to be compliant with WCAG AA 2.0
* [bmo#1798166](https://bugzilla.mozilla.org/show_bug.cgi?id=1798166)
I ran the devtools accessibility tools on the different pages.

Bug 1798166 - Fix color contrast to be compliant with WCAG AA 2.0

---

Bugzilla/Bug.pm
Bugzilla/DB.pm
Bugzilla/DB/Mysql.pm
Bugzilla/DB/Schema.pm
Bugzilla/DB/Schema/Mysql.pm
Bugzilla/DB/Schema/Sqlite.pm
Bugzilla/Group.pm
Bugzilla/Install/DB.pm
Bugzilla/Migrate.pm
Bugzilla/Object.pm
Bugzilla/Product.pm
Bugzilla/Search.pm
Bugzilla/User.pm
editgroups.cgi
editproducts.cgi
editusers.cgi
sanitycheck.cgi
userprefs.cgi
whine.pl

Quote the table name when it involves the `groups` table, since it is now considered to be a reserved word in modern versions of MySQL.
This commit was derived from the following one from BMO, in which  they use $dbh->quote_identifier(), which allows the different DBD::* drivers to use the appropriate quoting. https://github.com/mozilla-bteam/bmo/commit/5dc1b8c85c4e90c3467fd82cab9fca05fe2be74a
* [bmo#1592129](https://bugzilla.mozilla.org/show_bug.cgi?id=1592129)
* [bmo#1604051](https://bugzilla.mozilla.org/show_bug.cgi?id=1604051)
*  alternative to https://github.com/bugzilla/bugzilla/pull/107

[MYSQL8] The groups table in Bugzilla conflicts with reserved keyword in MySQL 8.x

---

Bugzilla/Config/Common.pm
Bugzilla/FlagType.pm
Bugzilla/Install/Requirements.pm
Bugzilla/Migrate/Gnats.pm
Bugzilla/Util.pm
email_in.pl

This patch updates us from using Email::Address to Email::Address::XS to resolve CVE-2015-7686.
Regex comparisons have been replaced by parse + is_valid calls as per current documentation.
* [bmo#1853138](https://bugzilla.mozilla.org/show_bug.cgi?id=1853138)
Test plan is a work in progress.. 😕

Bug 1853138 - Switch to Email::Address::XS

---

template/en/default/email/new-user-details.txt.tmpl

In an email notifying somebody of the creation of his Bugzilla account, this adds a non-breaking space between the Bugzilla url and the colon.
* [bmo#1342509](https://bugzilla.mozilla.org/show_bug.cgi?id=1342509)
1. Go to /editusers.cgi?action=add
2. Create a new user, ensuring "Notify User" is selected.
3. Read the received email

use a non-breaking space between the urlbase and the colon

---

Bugzilla/Hook.pm
Bugzilla/Template.pm
extensions/Example/Extension.pm

Reverts PR #60 because it adds a new feature which isn't valid on an old stable branch which should get bugfixes only. There has not been a release on this branch since it landed.
PR #60 did not have a valid bug linked to it either.

[5.0.4] Backout PR #60 - new feature not valid for stable branch

---

Bugzilla/Constants.pm
Bugzilla/DB.pm
Bugzilla/DB/MariaDB.pm
Bugzilla/DB/Schema/MariaDB.pm
Bugzilla/Install/Requirements.pm
Build.PL
docs/en/rst/installing/essential-post-install-config.rst
t/004template.t
template/en/default/config.js.tmpl
template/en/default/setup/strings.txt.pl

* Require MySQL 5.6.12 for InnoDB Fulltext support
* ~~Blocklist MySQL 8+ for groups issue~~
* Independently require MariaDB 10+ for InnoDB fulltext support
~~See [Bug 1851354](https://bugzilla.mozilla.org/show_bug.cgi?id=1851354)~~
See [Bug 868869](https://bugzilla.mozilla.org/show_bug.cgi?id=868869)

[5.2] Bug 868869: Require MySQL 5.6, Bug 1467006: explicit MariaDB support

---

Bugzilla/Constants.pm
Bugzilla/DB.pm
Bugzilla/Install/Requirements.pm
docs/en/rst/installing/essential-post-install-config.rst
t/004template.t
template/en/default/config.js.tmpl
template/en/default/setup/strings.txt.pl

See [Bug 1851354](https://bugzilla.mozilla.org/show_bug.cgi?id=1851354)
The patch on the bugzilla bug had not been r+'d yet.

[5.1] Bug 1851354: blocklist MySQL 8+, offer MariaDB

---

.gitignore

.DS_Store files are droppings from the Mac Finder and can be ignored.
* [bmo#1433029](https://bugzilla.mozilla.org/show_bug.cgi?id=1433029)

Bug 1433029: Ignore Mac Finder droppings

---

Bugzilla/DB.pm

Small postfix on 35a060cbd9d880541ad7e6c02710c0c3647a3b19 as MariaDB-11.0 removed the 5.5.5- replication prefix.
The reliable way to have MariaDB detected is looking for "-MariaDB" in the version string. Distro packages may add a suffix so an unanchored match is pretty reliable.
* [bmo#](https://bugzilla.mozilla.org/show_bug.cgi?id=)
1. Run against MariaDB-11.0+
2. See if it autodetects MariaDB as a module

Bug 1467006: explicit MariaDB support (#140) - version detection fix

---

Bugzilla/DB.pm
template/en/default/setup/strings.txt.pl

* [bmo#1896055](https://bugzilla.mozilla.org/show_bug.cgi?id=1896055)
1. Install MariaDB 10.6 or newer
2. Edit localconfig and set db_driver to 'mysql'
3. Run checksetup.pl
4. Should get warning that the DB engine is MariaDB and request to change db_driver to 'mariadb' in localconfig.

Bug 1896055: Don't talk to MariaDB with the MySQL driver

---

checksetup.pl

* [bmo#1896247](https://bugzilla.mozilla.org/show_bug.cgi?id=1896247)

Bug 1896247: Fix breakage from 5.1 upgrade check

---

Bugzilla/Install/Requirements.pm

* [bmo#1851352](https://bugzilla.mozilla.org/show_bug.cgi?id=1851352)

[4.4] Bug 1851352: Email::Address dependency missing

---

Bugzilla/Install/Requirements.pm

* [bmo#1851352](https://bugzilla.mozilla.org/show_bug.cgi?id=1851352)

[5.0.4] Bug 1851352: Email::Address dependency missing

---

Makefile.PL

* [bmo#1851352](https://bugzilla.mozilla.org/show_bug.cgi?id=1851352)

[5.3] Bug 1851352: Missing Email::Address dependency

---

Bugzilla/DB/Schema.pm
Bugzilla/Install/DB.pm

cherry-picked the Bug 1526703 patch from the 5.0.6 release, which was missing from 5.1/5.3
* [bmo#1634711](https://bugzilla.mozilla.org/show_bug.cgi?id=1634711)

[5.3] Bug 1634711: backport Bug 1526703 from 5.2 - Increase the size of the flagtype id column

---

docs/en/rst/installing/db_server.rst
docs/en/rst/installing/mariadb.rst
docs/en/rst/installing/mysql.rst

Updating db_server.rst and mysql.rst to more current information on mariadb
1. putting MariaDB first as it is the recommended database
2. Changed MySQL to MariaDB in title and running text, since Bugzilla is compatible with MariaDB
3. Changed text about being "MariaDB being drop in compatible with MySQL" to "fully compatible with Bugzilla."
4. Removed comment about MySQL 8.0 not being supported
5. Updated command for version testing to include both mariadb and mysql
6. Updated command line from mysql to mariadb (mentioning mysql first time) 
7. Removed "FLUSH PRIVILEGES;" - never needed with user modification SQL.
8. Removed comment about mysql_secure_installation, since not actively fixed in a while
9. Removed "Permit Attachments Table to Grow Beyond 4GB" as these settings are not …

Updating db_server.rst and mysql.rst regarding mariadb

---

template/en/default/global/common-links.html.tmpl
template/en/default/index.html.tmpl
template/en/default/pages/quicksearch.html.tmpl

Add aria-label to the quicksearch fields
* [bug#1874564](https://bugzilla.mozilla.org/show_bug.cgi?id=1874564)

Bug 1874564: QuickSearch inputs need labels

---

template/en/default/account/create.html.tmpl
template/en/default/global/common-links.html.tmpl
template/en/default/index.html.tmpl
template/en/default/pages/quicksearch.html.tmpl

Add label tag to existing label on the email address/login name field
* [bug#1848099](https://bugzilla.mozilla.org/show_bug.cgi?id=1848099)
Note: this depends on #177, it needs to land first.

Bug 1848099: Signup form email field needs a label

---

Bugzilla/Update.pm
template/en/default/index.html.tmpl

* [bug#1852154](https://bugzilla.mozilla.org/show_bug.cgi?id=1852154)
1. modify data/bugzilla-update.xml locally to add an eos-date="2024-09-20" to the 4.4 branch (example date, subject to change)
2. load the front page of Bugzilla while logged in as an administrator.
3. The message that security support will be ending on that date should appear.
4. Test with both stable_branch_release and latest_stable_release

[4.4] Bug 1852154: Warn admin if end-of-support date is approaching

---

Bugzilla/Update.pm
template/en/default/index.html.tmpl

* [bug#1852154](https://bugzilla.mozilla.org/show_bug.cgi?id=1852154)
1. modify data/bugzilla-update.xml locally to add an eos-date="2024-09-20" to the 5.0.4 branch (have to create the branch in the file, example date, subject to change)
2. load the front page of Bugzilla while logged in as an administrator.
3. The message that security support will be ending on that date should appear.
4. Test with both stable_branch_release and latest_stable_release

[5.0.4] Bug 1852154: Warn admin if end-of-support date is approaching

---

Bugzilla/Update.pm
template/en/default/index.html.tmpl

* [bug#1852154](https://bugzilla.mozilla.org/show_bug.cgi?id=1852154)
1. modify data/bugzilla-update.xml locally to add an eos-date="2024-09-20" to the 5.0 branch (example date, subject to change), also change the branch status to old-stable.
2. Create a 5.2 branch and make it stable.
3. load the front page of Bugzilla while logged in as an administrator.
4. The message that security support will be ending on that date should appear.
5. Test with both stable_branch_release and latest_stable_release

[5.2] Bug 1852154: Warn admin if end-of-support date is approaching

---

Bugzilla/Config/Common.pm
Bugzilla/Config/General.pm
Bugzilla/DB/MariaDB.pm
Bugzilla/DB/Mysql.pm
Bugzilla/DB/Schema/MariaDB.pm
template/en/default/admin/params/common.html.tmpl
template/en/default/admin/params/general.html.tmpl

* Test the DB for utf8 charset aliases
* fix column_info on MariaDB since it doesn't have mysql_ vars anymore
* change default encoding to utf8mb4 + utf8mb4_unicode_520_ci collation
* [bug#1898882](https://bugzilla.mozilla.org/show_bug.cgi?id=1898882)
1. Start with a database made with an older version of Bugzilla which is encoded in straight utf8
2. Run checksetup.pl
3. Ensure it converts to utf8mb4 properly, check utf8* params in data/params.json to verify values.

[5.2] Bug 1898882: UTF8 conv. issues with MySQL/MariaDB
